name: richiCoder Workflow
  run-name: workflow frontend 

on:
  push

jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: checking-secrets
        run: |
          echo
        env:
          CLAVE: ${{ secrets.CLAVE }}