name: richiCoder Workflow
  run-name: workflow frontend 

on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

pass-secret-to-workflow:
    uses: ./.github/workflows/secret
    secrets:
       token: ${{ secrets.CLAVE }}